### ISSUE TITLE
Visual Studio 2015 C++ compiler cannot compile certain constexpr constructions

### ISSUE THREAD

**Issue by hmaarrfk** [team-charls/charls#60]
https://github.com/team-charls/charls/blob/20ed9e93be8b035e992a049f0bd3b109443e23bd/src/util.h#L121

I'm getting an error on this line of code when trying to compile with VS 14.1

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=106870&view=logs&j=2cc45e14-23e3-52d7-b33a-8c2744410b97&t=21c44aa7-1ae3-5312-cacc-7f19fefc82f4&l=688

This build will likely get destroyed, so I'm copying the error message

```
[1/22] Building CXX object CMakeFiles\charls.dir\src\charls_jpegls_decoder.cpp.obj
FAILED: CMakeFiles/charls.dir/src/charls_jpegls_decoder.cpp.obj 
C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe  /nologo /TP -DCHARLS_LIBRARY_BUILD -Dcharls_EXPORTS -I..\include -MD -GL  /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MD /O2 /Ob2 /DNDEBUG   -std:c++14 /showIncludes /FoCMakeFiles\charls.dir\src\charls_jpegls_decoder.cpp.obj /FdCMakeFiles\charls.dir\ /FS -c ..\src\charls_jpegls_decoder.cpp
..\include\charls/charls.h(488): warning C4800: 'int32_t': forcing value to bool 'true' or 'false' (performance warning)
d:\bld\charls_1577727546940\work\src\util.h(121): error C3250: 'x': declaration is not allowed in 'constexpr' function body
d:\bld\charls_1577727546940\work\src\util.h(121): error C3249: illegal statement or sub-expression for 'constexpr' function
d:\bld\charls_1577727546940\work\src\util.h(122): error C3249: illegal statement or sub-expression for 'constexpr' function
d:\bld\charls_1577727546940\work\src\util.h(124): error C3249: illegal statement or sub-expression for 'constexpr' function
d:\bld\charls_1577727546940\work\src\util.h(124): note: see usage of '++'
d:\bld\charls_1577727546940\work\src\util.h(126): error C3256: 'x': variable use does not produce a constant expression
[2/22] Building CXX object CMakeFiles\charls.dir\src\charls_jpegls_encoder.cpp.obj
FAILED: CMakeFiles/charls.dir/src/charls_jpegls_encoder.cpp.obj 
C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe  /nologo /TP -DCHARLS_LIBRARY_BUILD -Dcharls_EXPORTS -I..\include -MD -GL  /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MD /O2 /Ob2 /DNDEBUG   -std:c++14 /showIncludes /FoCMakeFiles\charls.dir\src\charls_jpegls_encoder.cpp.obj /FdCMakeFiles\charls.dir\ /FS -c ..\src\charls_jpegls_encoder.cpp
..\include\charls/charls.h(488): warning C4800: 'int32_t': forcing value to bool 'true' or 'false' (performance warning)
d:\bld\charls_1577727546940\work\src\util.h(121): error C3250: 'x': declaration is not allowed in 'constexpr' function body
d:\bld\charls_1577727546940\work\src\util.h(121): error C3249: illegal statement or sub-expression for 'constexpr' function
d:\bld\charls_1577727546940\work\src\util.h(122): error C3249: illegal statement or sub-expression for 'constexpr' function
d:\bld\charls_1577727546940\work\src\util.h(124): error C3249: illegal statement or sub-expression for 'constexpr' function
d:\bld\charls_1577727546940\work\src\util.h(124): note: see usage of '++'
d:\bld\charls_1577727546940\work\src\util.h(126): error C3256: 'x': variable use does not produce a constant expression
[3/22] Building CXX object CMakeFiles\charls.dir\src\jpegls.cpp.obj
d:\bld\charls_1577727546940\work\src\scan.h(82): error C3249: illegal statement or sub-expression for 'constexpr' function
d:\bld\charls_1577727546940\work\src\scan.h(88): error C3250: 'mappedError': declaration is not allowed in 'constexpr' function body
d:\bld\charls_1577727546940\work\src\scan.h(88): error C3249: illegal statement or sub-expression for 'constexpr' function
ninja: build stopped: subcommand failed.

```

**Comment by hmaarrfk** [comment]
I think this might be because VS2015 might not implement all the features of constexpr

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3652.html

There are a few other declarations I had to make inline.

**Comment by vbaderks** [comment]
Yes, your right. VS2015 is not 100% C++14 compatible, but it still supported by Microsoft until October 2025. I will have a look.

**Comment by hmaarrfk** [comment]
If it helps, this is the patch i had to use:

https://github.com/conda-forge/charls-feedstock/blob/master/recipe/60-decleartion-constexpr.patch

**Comment by vbaderks** [comment]
Hi Mark,
Thanks for the patch. The version on the master branch now compiles with Visual Studio 2015.
This improvement will be included in v2.1.1. Is having this fix for you on the master branch enough?

**Comment by hmaarrfk** [comment]
Are you 100% sure that compiles? Without the `inline` word, I think I was having failures due to multiple definitions of the same function.

We can patch things up with conda-forge, and I can try out your patchc in a bit.

**Comment by vbaderks** [comment]
inline is used and needed for the free functions. In portable_anymap_file.h it is not needed as class member functions declared inside a class are auto inline. It compiles on my local VS 2015 setup.

I was already thinking of adding an Azure CI pipeline to ensure older versions of VS are auto tested, will give that task some more prio.

**Comment by hmaarrfk** [comment]
Hmm ok. Thanks for the detailed explanation. I didn't know about autoinline


Yeah moving to Azure is OK, you just have to want to buy into yet an other platform.

I'm trying to build with your patch now

https://github.com/conda-forge/charls-feedstock/pull/3#issuecomment-570095834

It seems to have worked.

**Comment by hmaarrfk** [comment]
You can close if you want.
