### ISSUE TITLE
wasm64

### ISSUE THREAD

**Issue by Nekto89** [team-charls/charls#350]
Hi,

I've tried to build CharLS with wasm64 and got compilation errors. Are there any plans to support it in future?

https://github.com/team-charls/charls/blob/367fea40f5a36195e974d677ec5b88581605bef1/src/util.hpp#L235C1-L235C70

**Comment by vbaderks** [comment]
PR #358 removed the workaround for emcc 3.1.1. As there is no special code anymore for wasm, wasm64 should work fine now.
As charls-js only supports wasm32 I can only confirm that removing works fine with emcc 4.0.23 in wasm32 mode.
